### ISSUE TITLE
ConfigCache nullable values?

### ISSUE THREAD

**Issue by valeriyo** [configcat/kotlin-sdk#1]
I migrated from `configcat-android-client` and it was quite strange that `interface ConfigCache` uses empty strings instead of `null` to indicate "no value". Please change it:

* `read` to return `String?` and
* `write` to take `value: String?`

This would be a breaking change, but I think it's worth getting it right.

**Comment by z4kn4fein** [comment]
Hi @valeriyo, thank you for reporting!
I'm planning to apply our ongoing SDK improvements (e.g. for swift [here](https://github.com/configcat/swift-sdk/pull/27)) to this SDK next. It'll include the success indication of `forceRefresh()` that you reported on the Android SDK and I'll also include the fix for this report.

**Comment by z4kn4fein** [comment]
Hi @valeriyo, we released a new version of the Kotlin SDK (`v1.0.2`) with fixes to the related issues. Feel free to let us know if you have more suggestions.

**Comment by z4kn4fein** [comment]
Hi @valeriyo, the SDK won't call `write()` when it doesn't have a valid value to cache. There's no such case as the SDK clearing the cache, it only writes the latest valid (non-empty and non-null) configuration into it.

**Comment by valeriyo** [comment]
Oh ok - so once a value is written, it will stay there forever (as long as the app is installed).. I guess that's expected?

**Comment by z4kn4fein** [comment]
Yep, the SDK derives the cache key by the SDK keys you use, so it'll use a single cache entry per SDK key. It'll overwrite the same entry when a config for an SDK key is updated.
