### ISSUE TITLE
Get Value is not useable from non-inline Functions

### ISSUE THREAD

**Issue by MrThreepwood** [configcat/kotlin-sdk#35]
### Is your feature request related to a problem? Please describe.

I would like to be able to fetch data from an interface implimentation. Interfaces don't have inline functions, and therefor can't have reified generic params.

### Describe the solution you'd like

Making a getValue function that can take a Class or KClass would be convenient.

### Describe alternatives you've considered

Currently I just have to use the Java SDK

**Comment by novalisdenahi** [comment]
Hi @MrThreepwood,

Thank you for your feedback!
I'll put this topic on our next dev meeting's agenda to discuss it with the team. I'll let you know about the results.

In the meantime, I think you should check the [getAnyValue method](https://github.com/configcat/kotlin-sdk/blob/4dad14bc9bb0288da76ca24f2c7a7d7fabca984b/src/commonMain/kotlin/com/configcat/ConfigCatClient.kt#L114).  This can be a solution for you as well I think.

Best Regards,
Daniel

**Comment by novalisdenahi** [comment]
Hi @MrThreepwood,

Have you tried the `getAnyValue `method? Is it a good solution for you?

If not, can you show me a quick code example of how you would like to use the new method with the Kclass<T> parameter or how you currently use the Java SDK `getValue`? 

Thanks in advance!
Daniel
