### ISSUE TITLE
Boolean feature flag overrides don't work

### ISSUE THREAD

**Issue by valeriyo** [configcat/kotlin-sdk#6]
A boolean feature flag, defaulted to `false`, overridden to `true`, comes out as `false`.

The problem is here (`ConfigCatClient.kt`):
```
public suspend inline fun <reified T: Any> ConfigCatClient.getValue(
    key: String,
    defaultValue: T,
    user: ConfigCatUser? = null
): T = this.getAnyValue(key, defaultValue, user) as? T ?: defaultValue
```

The `getAnyValue(key, defaultValue, user)` evaluates to "true" (String), and then cast to `Boolean` with `as?` which yields `null` - and then, it falls back to `defaultValue`, which is `false`. So, the "true" override doesn't work :(

**Comment by z4kn4fein** [comment]
Hi @valeriyo. Thank you for reaching out! 
Is it the case that you set the overridden value to `"true"` as `String`? The overrides take a `Map<String, Any>`, and the SDK doesn't change the `Any` values type. If you pass a `String` for a boolean flag's value, the conversion will fail. However, you can pass its value as a boolean, which will work correctly.

```kotlin
dataSource = OverrideDataSource.map(
    mapOf(
        key to true,
    )
)
```

**Comment by valeriyo** [comment]
You're totally right, I mixed up overrides with ConfigCache. Found the problem on my end and fixed it. Thanks!
